name: Build kdae amd64 3 variants

on:
  push:
    branches:
      - build-1d52465-2fb733f
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - goamd64: v1
            asset: linux-x86_64
          - goamd64: v2
            asset: linux-x86_64_v2_sse
          - goamd64: v3
            asset: linux-x86_64_v3_avx2
    runs-on: ubuntu-22.04
    env:
      GOOS: linux
      GOARCH: amd64
      GOAMD64: ${{ matrix.goamd64 }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: |
          date=$(git log -1 --format="%cd" --date=short | sed s/-//g)
          version="unstable-${date}.r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
          echo "VERSION=${version}" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-15 llvm-15

      - name: Get project dependencies
        run: |
          GOMODCACHE="${PWD}"/go-mod go mod download -modcacherw
          find ./go-mod/ -maxdepth 1 ! -name "cache" ! -name "go-mod" -exec rm -rf {} \;
          sed -i 's/#export GOMODCACHE=$(PWD)\/go-mod/export GOMODCACHE=$(PWD)\/go-mod/' Makefile

      - name: Build dae
        run: |
          mkdir -p ./build/
          export GOFLAGS="-trimpath -modcacherw"
          export GOEXPERIMENT="newinliner,simd,heapminimum512kib,randomizedheapbase64"
          export OUTPUT=build/dae-${{ matrix.asset }}
          export VERSION=${{ steps.get_version.outputs.VERSION }}
          export CLANG=clang-15
          export STRIP=llvm-strip-15
          make

      - name: Smoking test
        run: ./build/dae-${{ matrix.asset }} --version

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dae-${{ matrix.asset }}
          path: build/dae-${{ matrix.asset }}
